### ISSUE TITLE
Camera calibration and initial position

### ISSUE THREAD

**Issue by Hamdi-Ben-Abdallah** [huanghone/RBOTE#1]
Hello,

Thanks for sharing the data.
Can you share the camera calibration file and the initial poses for each data?

Thanks in advance.

**Comment by huanghone** [comment]
The camera calibration and poses are the same with the RBOT dataset.

**Comment by anchor654** [comment]
Is it possible to run "Pixel-Wise Weighted Region-Based 3D Object Tracking using Contour Constraints" code using only these png images?
